# Generated by Django 6.0.6 on 2026-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
