# Generated by Django 6.0.6 on 2026-08-08 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcore', '0002_application'),
        ('users', '0003_profile_resume_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='jobcore.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='users.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job', 'resume')},
            },
        ),
    ]
