# Generated by Django 6.0.6 on 2026-08-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcore', '0004_company_is_startup_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='keyword_match',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='resume_completeness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='skill_match',
            field=models.FloatField(default=0),
        ),
    ]
